nohup Rscript lr_human_bins_heatmap.R REST "site" > ./output/REST_site.out &
nohup Rscript lr_human_bins_heatmap.R REST "peak" > ./output/REST_peak.out &
nohup Rscript lr_human_bins_heatmap.R JUND "site" > ./output/JUND_site.out &
nohup Rscript lr_human_bins_heatmap.R JUND "peak" > ./output/JUND_peak.out &
nohup Rscript lr_human_bins_heatmap.R CTCF "site" > ./output/CTCF_site.out &
nohup Rscript lr_human_bins_heatmap.R CTCF "peak" > ./output/CTCF_peak.out &
nohup Rscript lr_human_bins_heatmap.R MAX "site" > ./output/MAX_site.out &
nohup Rscript lr_human_bins_heatmap.R MAX "peak" > ./output/MAX_peak.out &
nohup Rscript lr_human_bins_heatmap.R SRF "site" > ./output/SRF_site.out &
nohup Rscript lr_human_bins_heatmap.R SRF "peak" > ./output/SRF_peak.out &
nohup Rscript lr_human_bins_heatmap.R GABPA "site" > ./output/GABPA_site.out &
nohup Rscript lr_human_bins_heatmap.R GABPA "peak" > ./output/GABPA_peak.out &
